# Generated by Django 4.2.2 on 2023-06-17 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Movie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("year", models.IntegerField()),
                ("rated", models.CharField(max_length=50)),
                ("released", models.DateField()),
                ("runtime", models.CharField(max_length=50)),
                ("genre", models.CharField(max_length=255)),
                ("director", models.CharField(max_length=255)),
                ("writer", models.TextField()),
                ("actors", models.TextField()),
                ("plot", models.TextField()),
                ("language", models.CharField(max_length=100)),
                ("country", models.CharField(max_length=100)),
                ("awards", models.TextField()),
                ("poster", models.URLField()),
                ("ratings", models.JSONField()),
                ("metascore", models.IntegerField()),
                ("imdb_rating", models.DecimalField(decimal_places=1, max_digits=3)),
                ("imdb_votes", models.IntegerField()),
                ("imdb_id", models.CharField(max_length=20)),
                ("movie_type", models.CharField(max_length=50)),
                ("dvd", models.DateField()),
                ("box_office", models.CharField(max_length=100)),
                ("production", models.CharField(max_length=255)),
                ("website", models.URLField()),
                ("response", models.BooleanField()),
            ],
        ),
    ]
