# Generated by Django 4.2.2 on 2023-06-17 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("my_movie_awards", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="movie", name="actors",),
        migrations.RemoveField(model_name="movie", name="awards",),
        migrations.RemoveField(model_name="movie", name="box_office",),
        migrations.RemoveField(model_name="movie", name="country",),
        migrations.RemoveField(model_name="movie", name="director",),
        migrations.RemoveField(model_name="movie", name="dvd",),
        migrations.RemoveField(model_name="movie", name="genre",),
        migrations.RemoveField(model_name="movie", name="imdb_rating",),
        migrations.RemoveField(model_name="movie", name="imdb_votes",),
        migrations.RemoveField(model_name="movie", name="language",),
        migrations.RemoveField(model_name="movie", name="metascore",),
        migrations.RemoveField(model_name="movie", name="plot",),
        migrations.RemoveField(model_name="movie", name="production",),
        migrations.RemoveField(model_name="movie", name="rated",),
        migrations.RemoveField(model_name="movie", name="ratings",),
        migrations.RemoveField(model_name="movie", name="released",),
        migrations.RemoveField(model_name="movie", name="response",),
        migrations.RemoveField(model_name="movie", name="runtime",),
        migrations.RemoveField(model_name="movie", name="website",),
        migrations.RemoveField(model_name="movie", name="writer",),
        migrations.AlterField(
            model_name="movie", name="imdb_id", field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name="movie", name="year", field=models.CharField(max_length=4),
        ),
    ]
